_wandb:
    value:
        cli_version: 0.21.0
        e:
            7cco0s6zncyoommdphnwt6dmriksdi6d:
                args:
                    - data.batch_size=32
                    - data.image_size=[256, 256]
                    - model.dropout=0.2
                    - model.lr=0.008986812036013599
                    - model.name=resnet18
                    - model.weight_decay=0
                codePath: src/train/train.py
                codePathLocal: src/train/train.py
                cpu_count: 32
                cpu_count_logical: 64
                cudaVersion: "12.2"
                disk:
                    /:
                        total: "1964618686464"
                        used: "148860043264"
                email: jslkap227@gmail.com
                executable: /opt/conda/bin/python
                git:
                    commit: 5b430ebccba1aabe188dc222a68a407be1358b4f
                    remote: git@github.com:AIBootcamp13/upstageailab-cv-classification-cv_7.git
                gpu: NVIDIA GeForce RTX 3090
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10496
                      memoryTotal: "25769803776"
                      name: NVIDIA GeForce RTX 3090
                      uuid: GPU-76606eb2-b917-02b5-40cd-eced9752e25b
                host: instance-15551
                memory:
                    total: "270133542912"
                os: Linux-5.4.0-167-generic-x86_64-with-glibc2.31
                program: /data/ephemeral/home/upstageailab-cv-classification-cv_7/src/train/train.py
                python: CPython 3.10.13
                root: /data/ephemeral/home/upstageailab-cv-classification-cv_7
                startedAt: "2025-07-08T19:05:56.219817Z"
                writerId: 7cco0s6zncyoommdphnwt6dmriksdi6d
        m: []
        python_version: 3.10.13
        t:
            "1":
                - 1
                - 5
                - 9
                - 49
                - 50
                - 53
                - 80
                - 103
            "2":
                - 1
                - 5
                - 9
                - 49
                - 50
                - 53
                - 80
                - 103
            "3":
                - 14
                - 16
            "4": 3.10.13
            "5": 0.21.0
            "12": 0.21.0
            "13": linux-x86_64
data:
    value:
        apply_transform_prob: 0.8
        batch_size: 32
        data_dir: /data/ephemeral/home/upstageailab-cv-classification-cv_7/../../data
        image_normalization:
            mean:
                - 0.485
                - 0.456
                - 0.406
            std:
                - 0.229
                - 0.224
                - 0.225
        image_size:
            - 256
            - 256
        num_workers: 16
        persistent_workers: true
        pin_memory: true
        val_split: 0.2
data.batch_size:
    value: 32
data.image_size:
    value:
        - 256
        - 256
model:
    value:
        _target_: src.model.timm_model.TimmClassifier
        dropout: 0.2
        lr: 0.008986812036013599
        name: resnet18
        num_classes: 17
        weight_decay: 0
model.dropout:
    value: 0.2
model.lr:
    value: 0.008986812036013599
model.name:
    value: resnet18
model.weight_decay:
    value: 0
project_name:
    value: document-classification
seed:
    value: 42
train:
    value:
        data:
            batch_size: 32
            image_size:
                - 224
                - 224
        model:
            dropout: 0.3
            lr: 0.001
            name: resnet18
            weight_decay: 0.0001
        train:
            accelerator: gpu
            devices: 1
            log_every_n_steps: 10
            max_epochs: 25
            precision: 16
wandb:
    value:
        entity: CV-7
        mode: offline
        project: document-classification
        run_name: resnet18-2025-07-09_04-05-56
