wandb_version: 1

data.batch_size:
  value: 16
data.image_size:
  value:
  - 224
  - 224
model.dropout:
  value: 0.3
model.lr:
  value: 0.000248776950474877
model.name:
  value: resnet18
model.weight_decay:
  value: 0
