wandb_version: 1

data.batch_size:
  value: 64
data.image_size:
  value:
  - 256
  - 256
model.dropout:
  value: 0.5
model.lr:
  value: 0.005350010523158725
model.name:
  value: resnet18
model.weight_decay:
  value: 0
