wandb_version: 1

data.batch_size:
  value: 16
data.image_size:
  value:
  - 224
  - 224
model.dropout:
  value: 0.2
model.lr:
  value: 0.006231985490842068
model.name:
  value: resnet18
model.weight_decay:
  value: 1.0e-05
