wandb_version: 1

data.batch_size:
  value: 16
data.image_size:
  value:
  - 224
  - 224
model.dropout:
  value: 0.5
model.lr:
  value: 0.0034589231771225627
model.name:
  value: resnet18
model.weight_decay:
  value: 0
