wandb_version: 1

model.batch_size:
  value: 64
model.dropout:
  value: 0.2
model.image_size:
  value:
  - 256
  - 256
model.lr:
  value: 0.00770079537712761
model.name:
  value: resnet18
model.weight_decay:
  value: 0.0001
