wandb_version: 1

model.batch_size:
  value: 32
model.dropout:
  value: 0.3
model.image_size:
  value:
  - 256
  - 256
model.lr:
  value: 0.009533714767046913
model.name:
  value: resnet18
model.weight_decay:
  value: 1.0e-05
