wandb_version: 1

data.batch_size:
  value: 64
data.image_size:
  value:
  - 256
  - 256
model.dropout:
  value: 0.2
model.lr:
  value: 0.003872531140302428
model.name:
  value: resnet18
model.weight_decay:
  value: 1.0e-05
