wandb_version: 1

data.batch_size:
  value: 32
data.image_size:
  value:
  - 256
  - 256
model.dropout:
  value: 0.3
model.lr:
  value: 0.007455499276598996
model.name:
  value: resnet18
model.weight_decay:
  value: 1.0e-05
