wandb_version: 1

data.batch_size:
  value: 16
data.image_size:
  value:
  - 256
  - 256
model.dropout:
  value: 0.2
model.lr:
  value: 0.009463603094121377
model.name:
  value: resnet18
model.weight_decay:
  value: 0.0001
