wandb_version: 1

data.batch_size:
  value: 64
data.image_size:
  value:
  - 224
  - 224
model.dropout:
  value: 0.3
model.lr:
  value: 0.008828337531625402
model.name:
  value: resnet18
model.weight_decay:
  value: 1.0e-05
