wandb_version: 1

data.batch_size:
  value: 64
data.image_size:
  value:
  - 224
  - 224
model.dropout:
  value: 0.2
model.lr:
  value: 0.0016582905369497017
model.name:
  value: resnet18
model.weight_decay:
  value: 0.0001
