wandb_version: 1

data.batch_size:
  value: 32
data.image_size:
  value:
  - 256
  - 256
model.dropout:
  value: 0.2
model.lr:
  value: 0.0037307644014461672
model.name:
  value: resnet18
model.weight_decay:
  value: 0.0001
