wandb_version: 1

data.batch_size:
  value: 32
data.image_size:
  value:
  - 224
  - 224
model.dropout:
  value: 0.2
model.lr:
  value: 0.00972886347516612
model.name:
  value: resnet18
model.weight_decay:
  value: 0.0001
