_wandb:
    value:
        cli_version: 0.21.0
        e:
            44s7bcn24dj41bty6dwwtuyah9kudi4n:
                codePath: src/train/train_kfold.py
                codePathLocal: train_kfold.py
                cpu_count: 32
                cpu_count_logical: 64
                cudaVersion: "12.2"
                disk:
                    /:
                        total: "1964618686464"
                        used: "133011197952"
                email: jslkap227@gmail.com
                executable: /opt/conda/bin/python
                git:
                    commit: 1e08693331567e46305c57f0713bc45911c7105b
                    remote: git@github.com:AIBootcamp13/upstageailab-cv-classification-cv_7.git
                gpu: NVIDIA GeForce RTX 3090
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10496
                      memoryTotal: "25769803776"
                      name: NVIDIA GeForce RTX 3090
                      uuid: GPU-76606eb2-b917-02b5-40cd-eced9752e25b
                host: instance-15551
                memory:
                    total: "270133542912"
                os: Linux-5.4.0-167-generic-x86_64-with-glibc2.31
                program: /data/ephemeral/home/upstageailab-cv-classification-cv_7/src/train/train_kfold.py
                python: CPython 3.10.13
                root: .
                startedAt: "2025-07-07T19:37:03.082128Z"
                writerId: 44s7bcn24dj41bty6dwwtuyah9kudi4n
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "2": '*'
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.10.13
        t:
            "1":
                - 1
                - 5
                - 9
                - 41
                - 49
                - 50
                - 53
                - 63
                - 80
                - 103
            "2":
                - 1
                - 5
                - 9
                - 41
                - 49
                - 50
                - 53
                - 63
                - 80
                - 103
            "3":
                - 2
                - 7
                - 13
                - 16
                - 66
            "4": 3.10.13
            "5": 0.21.0
            "10":
                - 20
            "12": 0.21.0
            "13": linux-x86_64
data:
    value:
        batch_size: 64
        data_dir: /data/ephemeral/home/upstageailab-cv-classification-cv_7/src/train/../../data
        fold: 0
        fold_path: /data/ephemeral/home/upstageailab-cv-classification-cv_7/src/train/../../data/train_fold.csv
        num_folds: 5
        num_workers: 32
lr:
    value: 0.001
model:
    value:
        _target_: src.model.timm_model.TimmClassifier
        lr: 0.001
        name: swin_tiny_patch4_window7_224
        num_classes: 17
name:
    value: swin_tiny_patch4_window7_224
num_classes:
    value: 17
project_name:
    value: document-classification
seed:
    value: 42
train:
    value:
        accelerator: gpu
        devices: 1
        log_every_n_steps: 10
        max_epochs: 25
        precision: 16
wandb:
    value:
        entity: CV-7
        mode: offline
        project: document-classification
        run_name: swin_tiny_patch4_window7_224-2025-07-08_04-32-00
