wandb_version: 1

data.batch_size:
  value: 64
data.image_size:
  value:
  - 384
  - 384
model.dropout:
  value: 0.3
model.lr:
  value: 0.003911050071126959
model.name:
  value: resnet18
model.weight_decay:
  value: 0
