wandb_version: 1

data.batch_size:
  value: 16
data.image_size:
  value:
  - 384
  - 384
model.dropout:
  value: 0.3
model.lr:
  value: 0.000827563352086682
model.name:
  value: resnet18
model.weight_decay:
  value: 0.0001
