defaults:
  - model: resnet18_sangho
  - data: document
  - train@train_cfg: default
  - wandb: wandb

project_name: document-classification
seed: 42

hydra:
  run:
    dir: ./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    chdir: False