wandb_version: 1

data.batch_size:
  value: 16
data.image_size:
  value:
  - 256
  - 256
model.dropout:
  value: 0.5
model.lr:
  value: 0.0022116826392989926
model.name:
  value: resnet18
model.weight_decay:
  value: 1.0e-05
