wandb_version: 1

data.batch_size:
  value: 32
data.image_size:
  value:
  - 256
  - 256
model.dropout:
  value: 0.5
model.lr:
  value: 0.0025828109033088176
model.name:
  value: resnet18
model.weight_decay:
  value: 0
