program: src/train/train.py
command:
  - ${program}
  - ${args_no_hyphens}
  
method: bayes # grid, random, bayes 가능
metric:
  name: val/f1
  goal: maximize

parameters:
  data.batch_size:
    values: [16, 32, 64]

  data.image_size:
    values:
      - [224, 224]
      - [256, 256]
      - [384, 384]
      
  model.lr:
    distribution: uniform
    min: 0.00001
    max: 0.01

  model.weight_decay:
    values: [0.0, 0.00001, 0.0001]

  model.dropout:
    values: [0.2, 0.3, 0.5]

  model.name:
    value: resnet18